name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.32.4"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Create config files
      run: |
        cp lib/core/config/app_config.dart.example lib/core/config/app_config.dart
        cp lib/core/config/firebase_options.dart.example lib/core/config/firebase_options.dart
        sed -i 's/YOUR_GOOGLE_CLIENT_ID_HERE/${{ secrets.GOOGLE_CLIENT_ID }}/g' lib/core/config/app_config.dart
        sed -i 's/YOUR_WEB_API_KEY_HERE/${{ secrets.FIREBASE_API_KEY }}/g' lib/core/config/firebase_options.dart
        sed -i 's/YOUR_WEB_APP_ID_HERE/${{ secrets.FIREBASE_APP_ID }}/g' lib/core/config/firebase_options.dart
        sed -i 's/YOUR_MESSAGING_SENDER_ID_HERE/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' lib/core/config/firebase_options.dart
        sed -i 's/YOUR_MEASUREMENT_ID_HERE/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g' lib/core/config/firebase_options.dart

    - name: Build Web
      run: flutter build web --release --base-href /auto30_next/
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 